### Authentication USER
POST {{url}}/api/auth/login
Content-Type: application/json

{
  "username": "{{user_username}}",
  "password": "{{user_password}}"
}

> {%
    import {verifyReturnCode} from "common.js";
    verifyReturnCode(client, response, 200);
    const {user, token} = response.body;
    const {id, username, role, createdAt, isAdmin } = user;
    client.global.set("user-token", token);
    client.log(`"Loggued as ${username} (${role}) : user-token is ${token}`);
%}
