### Verify admin-token
# 2.0.17 : bug for /auth/verify, it accepts GET instead of POST. Will be fixed in the next version, but use GET for now
GET {{url}}/api/auth/verify
Authorization: Bearer {{admin-token}}

> {%
     const {id, username, role, isAdmin } = response.body;
     const token = client.global.get("admin-token")
     client.log(`"Loggued as ${username} (role:${role})`);
%}

### Verify user-token
GET {{url}}/api/auth/verify
Authorization: Bearer {{user-token}}

> {%
     const {id, username, role, isAdmin } = response.body;
     const token = client.global.get("user-token")
     client.log(`"Loggued as ${username} (role:${role})`);
%}
