### As admin GET current_website_id /events + Set StartAt to now-1week...endAt:now
< {%
    const now = Date.now();
    const oneDaySec = 24 * 60 * 60 * 1000;
    const oneWeekAgo = now - 7 * oneDaySec;
    client.global.set("startAt", oneWeekAgo);
    client.global.set("endAt", now);
    console.log(`StartAt: ${oneWeekAgo} (${new Date(oneWeekAgo).toUTCString()})`);
    console.log(`EndAt: ${now} (${new Date(now).toUTCString()})`);
%}
GET {{url}}/api/websites/{{current_website_id}}/events?startAt={{startAt}}&endAt={{endAt}}&unit=hour&tz={{tz}}
Authorization: Bearer {{admin-token}}

### As admin GET current_website_id /events
GET {{url}}/api/websites/{{current_website_id}}/events?startAt={{startAt}}&endAt={{endAt}}&unit=hour&tz={{tz}}
Authorization: Bearer {{admin-token}}

### As admin GET current_website_id /event-data/events
GET {{url}}/api/websites/{{current_website_id}}/event-data/events?startAt={{startAt}}&endAt={{endAt}}
Authorization: Bearer {{admin-token}}

### As admin GET current_website_id /event-data/fields
GET {{url}}/api/websites/{{current_website_id}}/event-data/fields?startAt={{startAt}}&endAt={{endAt}}
Authorization: Bearer {{admin-token}}

### As admin GET current_website_id /event-data/values
GET {{url}}/api/websites/{{current_website_id}}/event-data/fields?startAt={{startAt}}&endAt={{endAt}}
Authorization: Bearer {{admin-token}}

### As admin GET current_website_id /event-data/stats
GET {{url}}/api/websites/{{current_website_id}}/event-data/stats?startAt={{startAt}}&endAt={{endAt}}
Authorization: Bearer {{admin-token}}